---
version: "2.1"
services:
  notes:
    image: nicholaswilde/notes:latest
    container_name: notes-default
    ports:
      - 8000:8000
    restart: unless-stopped
    volumes:
      - data:/data
volumes:
  data:
